Consent form updated to use jobTitle and companyName parameters
MagnumOpuses/af-connect pull request #57
Opened 2021-03-17 12:09 UTC by mobimation-gunnar

AF Connect API updated to include Job Title and Company Name
needed for the consent form in approving use
of AF user profile data.
These values arrive part of a data sink.
```
      <div><b>JobTechDev</b> får bara använda informationen för följande syfte:</div>
      <ul style="margin-top: 16px">
          <% data.sink.purposeOfUse.forEach((purpose) => { %>
              <li><%= purpose %></li>
          <% }) %>
      </ul>
```

af-connect handles rendering of the consent form.

2021-03-17 13:35 UTC, ixuz requested changes
1. Render `<%= data.sink.sinkName %>` here: https://github.com/MagnumOpuses/af-connect/blob/forrr-new-params-consent/app/views/partials/consentForm.ejs#L174
2. Render `<%= data.sink.sinkName %>` here: https://github.com/MagnumOpuses/af-connect/blob/forrr-new-params-consent/app/views/partials/consentForm.ejs#L177

2021-03-19 12:17 UTC, mobimation-gunnar commented
See those double pushes. I got confused. The first one 
b08ef38 is probably sufficient.

2021-03-19 13:54 UTC, ixuz commented on app/views/partials/consentForm.ejs
> +                  <div><input id="transferAgreement" type="checkbox" onclick="transferAgreement();"> Jag ger mitt medgivande att Arbetsförmedlingen får hantera och överföra dessa uppgifter till <b><%
```suggestion
                  <div><input id="transferAgreement" type="checkbox" onclick="transferAgreement();"> Jag ger mitt medgivande att Arbetsförmedlingen får hantera och överföra dessa uppgifter till <b><%= data.sink.sinkName %></b>.</div>

```

2021-03-19 13:55 UTC, ixuz commented on app/views/partials/consentForm.ejs
> +                  <div><input id="reviewAgreement" type="checkbox" onclick="reviewAgreement();"> Jag har granskat uppgifterna och bekräftar att inga oönskade uppgifter ingår i överföringen till <b><%
```suggestion
                  <div><input id="reviewAgreement" type="checkbox" onclick="reviewAgreement();"> Jag har granskat uppgifterna och bekräftar att inga oönskade uppgifter ingår i överföringen till <b><%= data.sink.sinkName %></b>.</div>

```

2021-03-19 13:57 UTC, ixuz approved these changes
Looks good

2021-03-20 22:32 UTC, merged