Forrr connect UI
MagnumOpuses/af-connect pull request #62
Opened 2021-05-27 12:44 UTC by mobimation-gunnar

(Thanks for sending a pull request! Please make sure you click the link above to view the [contribution guidelines](CONTRIBUTING.md), then fill out the blanks below.)

---

UI implementation according to PDF for Connect Once service.

...

It opens up the possibility to begin closing some issues.
...

**Any relevant logs, error output, etc?**

...

Part of changes that affect af-connect-module as well
...

**Where has this been tested?**
 - Macbook Pro 15 (2017)
 - **OS:** Catalina 10.15.7
 - **Browser:** Chrome
 - **Version:** 91.0.4472.77 (Official Build) (x86_64)

2021-06-01 07:32 UTC, ixuz requested changes
- Remove `app/public/img/graphics`
- Remove `app/views/pages/index-ny.ejs`
-

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.bundle.js
> +  console.log("GF:getSessionToken");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.bundle.js
> +  console.log("secrecyAgreement");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.bundle.js
> +  console.log("transferAgreement");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.bundle.js
> +  console.log("reviewAgreement");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.bundle.js
> +  console.log("openTermsAgreement");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.bundle.js
> +  console.log("onTermsAgreement");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.bundle.js
> +  console.log("onTermsCancel");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.js
> +  console.log("GF:getSessionToken");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.js
> +  console.log("secrecyAgreement");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.js
> +  console.log("transferAgreement");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.js
> +  console.log("reviewAgreement");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.js
> +  console.log("openTermsAgreement");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.js
> +  console.log("onTermsAgreement");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/public/js/main.js
> +  console.log("onTermsCancel");
Remove this console log

2021-06-01 07:32 UTC, ixuz commented on app/views/partials/consentForm.ejs
> +    function showPage(number) {
Move this function to `app/public/js/main.js`

2021-06-01 07:32 UTC, ixuz commented on app/views/partials/consentForm.ejs
> +    function clearBoxes() {
Move this function to `app/public/js/main.js`

2021-06-01 07:32 UTC, ixuz commented on app/views/partials/consentForm.ejs
> +    function consent() {
Move this function to `app/public/js/main.js`

2021-06-01 21:31 UTC, mobimation-gunnar commented on app/public/js/main.bundle.js
> +  console.log("secrecyAgreement");
Done.

2021-06-01 21:31 UTC, mobimation-gunnar commented on app/public/js/main.bundle.js
> +  console.log("reviewAgreement");
Done.

2021-06-01 21:31 UTC, mobimation-gunnar commented on app/public/js/main.js
> +  console.log("onTermsAgreement");
Done.

2021-06-01 21:32 UTC, mobimation-gunnar commented on app/public/js/main.js
> +  console.log("onTermsCancel");
Done.

2021-06-01 21:33 UTC, mobimation-gunnar commented on app/views/partials/consentForm.ejs
> +    function clearBoxes() {
Done.

2021-06-01 21:34 UTC, mobimation-gunnar commented on app/views/partials/consentForm.ejs
> +    function consent() {
Done.  <script> section removed from consentForm.ejs

2021-06-01 21:48 UTC, mobimation-gunnar commented
Pushed update

2021-06-03 07:13 UTC, ixuz approved these changes

2021-06-03 08:23 UTC, merged